Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
array = np.arange(2,51,3)
print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


 Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
import numpy as np
array1=[] 
array2=[]
for each in range(0, 5): 
    element = int(input("list1\n"))
    array1.append(element)
for each in range(0, 5): 
    element = int(input("list2\n"))
    array2.append(element) 
array1 = np.array(array1)
array2 = np.array(array2)
print(np.concatenate((array1,array2)))
print(np.sort(np.concatenate((array1,array2))))

list1
4
list1
5
list1
6
list1
7
list1
8
list2
1
list2
9
list2
3
list2
2
list2
0
[4 5 6 7 8 1 9 3 2 0]
[0 1 2 3 4 5 6 7 8 9]


Write a code snippet to find the dimensions of a ndarray and its size.

In [3]:
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array.ndim)
print(array.size)

2
9


How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet Hint: np.newaxis, np.expand_dims

In [4]:
import numpy as np
array=np.random.rand(5,)
print(array.ndim)
new_array = array[np.newaxis, :]
print(new_array.ndim)

1
2


Consider two square numpy arrays. Stack them vertically and horizontally. Hint: Use vstack(), hstack()

In [5]:
import numpy as np
array1=np.random.rand(3,3)
array2=np.random.rand(3,3)
print(np.vstack((array1,array2)))
print() #giving space
print(np.hstack((array1,array2)))

[[0.16911831 0.1666187  0.50802939]
 [0.14430495 0.46044472 0.78687586]
 [0.09179893 0.26453047 0.25707098]
 [0.31234619 0.99628827 0.38663441]
 [0.11558085 0.00451345 0.56135063]
 [0.18304828 0.78030369 0.03362533]]

[[0.16911831 0.1666187  0.50802939 0.31234619 0.99628827 0.38663441]
 [0.14430495 0.46044472 0.78687586 0.11558085 0.00451345 0.56135063]
 [0.09179893 0.26453047 0.25707098 0.18304828 0.78030369 0.03362533]]


 How to get unique items and counts of unique items?

In [6]:
import numpy as np
arr = np.array([1,9,3,1,5,2,5,6,4,3,9,7,6,8,9,2,6,5,6,3,8,9,7,8])
print(np.unique(arr,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 2, 3, 1, 3, 4, 2, 3, 4], dtype=int64))
